artifact_uri: file:///C:/Users/H%20P/Desktop/Real_Estate_Investment_Advisor_Using_ML_Streamlit/ML_runs_modular/356047125666740556/7b2ee4cd89d04a929145b5fda44086e5/artifacts
end_time: 1765012084509
entry_point_name: ''
experiment_id: '356047125666740556'
lifecycle_stage: active
run_id: 7b2ee4cd89d04a929145b5fda44086e5
run_name: rf_lgbm_baseline
source_name: ''
source_type: 4
source_version: ''
start_time: 1765012033977
status: 3
tags: []
user_id: H P
