artifact_uri: file:///C:/Users/H%20P/Desktop/Real_Estate_Investment_Advisor_Using_ML_Streamlit/ML_runs_modular/356047125666740556/c31ab736be664b42846ceac2945444fe/artifacts
end_time: 1765011450895
entry_point_name: ''
experiment_id: '356047125666740556'
lifecycle_stage: active
run_id: c31ab736be664b42846ceac2945444fe
run_name: rf_lgbm_baseline
source_name: ''
source_type: 4
source_version: ''
start_time: 1765011414860
status: 4
tags: []
user_id: H P
