artifact_location: file:///C:/Users/H%20P/Desktop/Real_Estate_Investment_Advisor_Using_ML_Streamlit/ML_runs_modular/356047125666740556
creation_time: 1765010972838
experiment_id: '356047125666740556'
last_update_time: 1765010972838
lifecycle_stage: active
name: real_estate_investment
