artifact_location: file:///C:/Users/H%20P/Desktop/Real_Estate_Investment_Advisor_Using_ML_Streamlit/ML_runs_modular/0
creation_time: 1765010972787
experiment_id: '0'
last_update_time: 1765010972787
lifecycle_stage: active
name: Default
