artifact_uri: file:///C:/Users/H%20P/Desktop/Real_Estate_Investment_Advisor_Using_ML_Streamlit/ML_runs_modular/356047125666740556/a44c529f75a74aeb989ab22059295002/artifacts
end_time: 1765011227395
entry_point_name: ''
experiment_id: '356047125666740556'
lifecycle_stage: active
run_id: a44c529f75a74aeb989ab22059295002
run_name: rf_lgbm_baseline
source_name: ''
source_type: 4
source_version: ''
start_time: 1765011189836
status: 4
tags: []
user_id: H P
