artifact_uri: file:///C:/Users/H%20P/Desktop/Real_Estate_Investment_Advisor_Using_ML_Streamlit/ML_runs_modular/356047125666740556/b3adbb835c2145f2bd3423cc98996606/artifacts
end_time: 1765011908184
entry_point_name: ''
experiment_id: '356047125666740556'
lifecycle_stage: active
run_id: b3adbb835c2145f2bd3423cc98996606
run_name: rf_lgbm_baseline
source_name: ''
source_type: 4
source_version: ''
start_time: 1765011844481
status: 3
tags: []
user_id: H P
