artifact_uri: file:///C:/Users/H%20P/Desktop/Real_Estate_Investment_Advisor_Using_ML_Streamlit/ML_runs_modular/356047125666740556/3ba6cfa9db1246df9d8b62953713b373/artifacts
end_time: 1765010973953
entry_point_name: ''
experiment_id: '356047125666740556'
lifecycle_stage: active
run_id: 3ba6cfa9db1246df9d8b62953713b373
run_name: rf_lgbm_baseline
source_name: ''
source_type: 4
source_version: ''
start_time: 1765010973682
status: 4
tags: []
user_id: H P
