artifact_uri: file:///C:/Users/H%20P/Desktop/Real_Estate_Investment_Advisor_Using_ML_Streamlit/ML_runs_modular/356047125666740556/f0692aa6e0aa4e40819644fe70da9741/artifacts
end_time: 1765011123504
entry_point_name: ''
experiment_id: '356047125666740556'
lifecycle_stage: active
run_id: f0692aa6e0aa4e40819644fe70da9741
run_name: rf_lgbm_baseline
source_name: ''
source_type: 4
source_version: ''
start_time: 1765011084378
status: 4
tags: []
user_id: H P
